In [1]:
import numpy as np # numpy is commonly used to process number array

X = np.array(([2, 9], [1, 5], [3, 6]), dtype=float) # Features ( Hrs Slept, Hrs Studied) 
y = np.array(([92], [86], [89]), dtype=float)	# Labels(Marks obtained)

X = X/np.amax(X,axis=0) # Normalize 
y = y/100

def sigmoid(x):
    return 1/(1 + np.exp(-x))
def sigmoid_grad(x):
    return x * (1 - x)

# Variable initialization
epoch=100	#Setting training iterations
eta =0.2		#Setting learning rate (eta)
input_neurons = 2	#number of features in data set 
hidden_neurons = 3	#number of hidden layers neurons
output_neurons = 1	#number of neurons at output layer

# Weight and bias - Random initialization
wh=np.random.uniform(size=(input_neurons,hidden_neurons))	# 2x3 
bh=np.random.uniform(size=(1,hidden_neurons))	# 1x3 
wout=np.random.uniform(size=(hidden_neurons,output_neurons)) # 1x1 
bout=np.random.uniform(size=(1,output_neurons))

for i in range(epoch):
#Forward Propogation
    h_ip=np.dot(X,wh) + bh	# Dot product + bias 
    h_act = sigmoid(h_ip)	# Activation function 
    o_ip=np.dot(h_act,wout) + bout
    output = sigmoid(o_ip)

#Backpropagation
    # Error at Output layer
    Eo = y-output	# Error at o/p 
    outgrad = sigmoid_grad(output)
    d_output = Eo* outgrad	# Errj=Oj(1-Oj)(Tj-Oj)

    # Error at Hidden later
    Eh = d_output.dot(wout.T)	# .T means transpose
    hiddengrad = sigmoid_grad(h_act)	# How much hidden layer wts contributed to error 
    d_hidden = Eh * hiddengrad
    wout += h_act.T.dot(d_output) *eta	# Dotproduct of nextlayererror and currentlayerop 
    wh += X.T.dot(d_hidden) *eta
    print("Error in "+str(i)+" iteration: \n",abs(y-output))
    
print("Normalized Input: \n" + str(X))
print("Actual Output: \n" + str(y))
print("Predicted Output: \n" ,output)
print("Final Error: \n" ,abs(y-output))

Error in 0 iteration: 
 [[0.25061231]
 [0.19913139]
 [0.22023632]]
Error in 1 iteration: 
 [[0.24056074]
 [0.1897113 ]
 [0.2102729 ]]
Error in 2 iteration: 
 [[0.23123207]
 [0.18095518]
 [0.20102537]]
Error in 3 iteration: 
 [[0.22256083]
 [0.17280367]
 [0.19242887]]
Error in 4 iteration: 
 [[0.21448756]
 [0.16520277]
 [0.1844245 ]]
Error in 5 iteration: 
 [[0.20695847]
 [0.15810363]
 [0.17695897]]
Error in 6 iteration: 
 [[0.19992505]
 [0.15146212]
 [0.16998427]]
Error in 7 iteration: 
 [[0.19334365]
 [0.14523848]
 [0.16345717]]
Error in 8 iteration: 
 [[0.187175  ]
 [0.13939694]
 [0.15733882]]
Error in 9 iteration: 
 [[0.18138382]
 [0.13390527]
 [0.15159427]]
Error in 10 iteration: 
 [[0.17593836]
 [0.12873449]
 [0.14619212]]
Error in 11 iteration: 
 [[0.17081008]
 [0.12385848]
 [0.14110411]]
Error in 12 iteration: 
 [[0.16597327]
 [0.11925369]
 [0.1363048 ]]
Error in 13 iteration: 
 [[0.16140475]
 [0.11489887]
 [0.13177124]]
Error in 14 iteration: 
 [[0.15708361]
 [0.11077481]
 [0.1